"""baseline

Revision ID: 5339f2871fae
Revises: 
Create Date: 2026-04-29 07:03:30.720864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5339f2871fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_source_group_status'), table_name='source_group')
    op.drop_index(op.f('idx_source_group_type'), table_name='source_group')
    op.drop_table('source_group')
    op.drop_index(op.f('idx_funnel_group_campaign'), table_name='funnel_group')
    op.drop_index(op.f('idx_funnel_group_type'), table_name='funnel_group')
    op.drop_table('funnel_group')
    op.alter_column('account', 'combat_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'cannon'::character varying"))
    op.alter_column('account', 'health_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('account', 'daily_action_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_account_combat_role'), table_name='account')
    op.drop_index(op.f('idx_account_health_score'), table_name='account')
    op.create_index(op.f('ix_account_auto_reply'), 'account', ['auto_reply'], unique=False)
    op.create_index(op.f('ix_account_combat_role'), 'account', ['combat_role'], unique=False)
    op.create_index(op.f('ix_account_cooldown_until'), 'account', ['cooldown_until'], unique=False)
    op.create_index(op.f('ix_account_created_at'), 'account', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_health_score'), 'account', ['health_score'], unique=False)
    op.create_index(op.f('ix_account_last_active'), 'account', ['last_active'], unique=False)
    op.create_index(op.f('ix_account_proxy_id'), 'account', ['proxy_id'], unique=False)
    op.create_index(op.f('ix_account_status'), 'account', ['status'], unique=False)
    op.drop_index(op.f('idx_accountsendstats_account_id'), table_name='accountsendstats')
    op.drop_index(op.f('idx_accountsendstats_stat_date'), table_name='accountsendstats')
    op.drop_index(op.f('idx_kb_name'), table_name='ai_knowledge_base')
    op.alter_column('ai_persona', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'system_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('ai_persona', 'tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'friendly'::character varying"))
    op.alter_column('ai_persona', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'zh'::character varying"))
    op.alter_column('ai_persona', 'forbidden_topics',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'required_keywords',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_persona', 'avg_reply_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_persona_name'), 'ai_persona', ['name'], unique=False)
    op.alter_column('campaign', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('campaign', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('campaign', 'allowed_roles',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'cannon,scout'::text"))
    op.alter_column('campaign', 'daily_budget',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    op.alter_column('campaign', 'daily_account_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('campaign', 'total_messages_sent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'total_replies_received',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'total_conversions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('campaign', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_campaign_status'), table_name='campaign')
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.alter_column('invitetask', 'total_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'privacy_restricted_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'flood_wait_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'pending_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'max_invites_per_task',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('invitetask', 'concurrent_accounts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('invitetask', 'stop_on_flood',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'filter_tags',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('invitetask', 'filter_funnel_stages',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('invitetask', 'exclude_invited',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'exclude_failed_recently',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'failed_cooldown_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('72'))
    op.alter_column('invitetask', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invitetask', 'recurring_interval_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('24'))
    op.alter_column('invitetask', 'recurring_batch_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.create_index(op.f('ix_proxy_category'), 'proxy', ['category'], unique=False)
    op.create_index(op.f('ix_proxy_country'), 'proxy', ['country'], unique=False)
    op.create_index(op.f('ix_proxy_created_at'), 'proxy', ['created_at'], unique=False)
    op.create_index(op.f('ix_proxy_expire_time'), 'proxy', ['expire_time'], unique=False)
    op.create_index(op.f('ix_proxy_last_checked'), 'proxy', ['last_checked'], unique=False)
    op.create_index(op.f('ix_proxy_provider_type'), 'proxy', ['provider_type'], unique=False)
    op.create_index(op.f('ix_proxy_status'), 'proxy', ['status'], unique=False)
    op.create_index(op.f('ix_sendrecord_account_id'), 'sendrecord', ['account_id'], unique=False)
    op.create_index(op.f('ix_sendrecord_sent_at'), 'sendrecord', ['sent_at'], unique=False)
    op.create_index(op.f('ix_sendrecord_status'), 'sendrecord', ['status'], unique=False)
    op.create_index(op.f('ix_sendrecord_target_user_id'), 'sendrecord', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_sendrecord_task_id'), 'sendrecord', ['task_id'], unique=False)
    op.create_index(op.f('ix_sendtask_created_at'), 'sendtask', ['created_at'], unique=False)
    op.create_index(op.f('ix_sendtask_status'), 'sendtask', ['status'], unique=False)
    op.alter_column('targetuser', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('targetuser', 'ai_tags',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('targetuser', 'ai_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('targetuser', 'funnel_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'raw'::character varying"))
    op.alter_column('targetuser', 'invite_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'untried'::character varying"))
    op.alter_column('targetuser', 'invite_attempt_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_targetuser_ai_score'), table_name='targetuser')
    op.drop_index(op.f('idx_targetuser_funnel_stage'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_telegram_id'), table_name='targetuser')
    op.create_index(op.f('ix_targetuser_telegram_id'), 'targetuser', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_targetuser_ai_score'), 'targetuser', ['ai_score'], unique=False)
    op.create_index(op.f('ix_targetuser_created_at'), 'targetuser', ['created_at'], unique=False)
    op.create_index(op.f('ix_targetuser_engagement_score'), 'targetuser', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_targetuser_funnel_stage'), 'targetuser', ['funnel_stage'], unique=False)
    op.create_index(op.f('ix_targetuser_last_hit_at'), 'targetuser', ['last_hit_at'], unique=False)
    op.create_index(op.f('ix_targetuser_marketing_stage'), 'targetuser', ['marketing_stage'], unique=False)
    op.create_index(op.f('ix_targetuser_source_group'), 'targetuser', ['source_group'], unique=False)
    op.create_index(op.f('ix_targetuser_source_group_id'), 'targetuser', ['source_group_id'], unique=False)
    op.create_index(op.f('ix_targetuser_status'), 'targetuser', ['status'], unique=False)
    op.create_index(op.f('ix_targetuser_username'), 'targetuser', ['username'], unique=False)
    op.alter_column('user', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_targetuser_username'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_status'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_source_group_id'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_source_group'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_marketing_stage'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_last_hit_at'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_funnel_stage'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_engagement_score'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_created_at'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_ai_score'), table_name='targetuser')
    op.drop_index(op.f('ix_targetuser_telegram_id'), table_name='targetuser')
    op.create_index(op.f('ix_targetuser_telegram_id'), 'targetuser', ['telegram_id'], unique=False)
    op.create_index(op.f('idx_targetuser_funnel_stage'), 'targetuser', ['funnel_stage'], unique=False)
    op.create_index(op.f('idx_targetuser_ai_score'), 'targetuser', ['ai_score'], unique=False)
    op.alter_column('targetuser', 'invite_attempt_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('targetuser', 'invite_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'untried'::character varying"))
    op.alter_column('targetuser', 'funnel_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'raw'::character varying"))
    op.alter_column('targetuser', 'ai_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('targetuser', 'ai_tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('targetuser', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_sendtask_status'), table_name='sendtask')
    op.drop_index(op.f('ix_sendtask_created_at'), table_name='sendtask')
    op.drop_index(op.f('ix_sendrecord_task_id'), table_name='sendrecord')
    op.drop_index(op.f('ix_sendrecord_target_user_id'), table_name='sendrecord')
    op.drop_index(op.f('ix_sendrecord_status'), table_name='sendrecord')
    op.drop_index(op.f('ix_sendrecord_sent_at'), table_name='sendrecord')
    op.drop_index(op.f('ix_sendrecord_account_id'), table_name='sendrecord')
    op.drop_index(op.f('ix_proxy_status'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_provider_type'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_last_checked'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_expire_time'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_created_at'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_country'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_category'), table_name='proxy')
    op.alter_column('invitetask', 'recurring_batch_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('invitetask', 'recurring_interval_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('24'))
    op.alter_column('invitetask', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('invitetask', 'failed_cooldown_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('72'))
    op.alter_column('invitetask', 'exclude_failed_recently',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'exclude_invited',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'filter_funnel_stages',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invitetask', 'filter_tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invitetask', 'stop_on_flood',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('invitetask', 'concurrent_accounts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('invitetask', 'max_invites_per_task',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('invitetask', 'pending_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'flood_wait_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'privacy_restricted_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invitetask', 'total_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.create_index(op.f('idx_campaign_status'), 'campaign', ['status'], unique=False)
    op.alter_column('campaign', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('campaign', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('campaign', 'total_conversions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'total_replies_received',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'total_messages_sent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign', 'daily_account_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('campaign', 'daily_budget',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('campaign', 'allowed_roles',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'cannon,scout'::text"))
    op.alter_column('campaign', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('campaign', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_persona_name'), table_name='ai_persona')
    op.alter_column('ai_persona', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_persona', 'avg_reply_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('ai_persona', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_persona', 'required_keywords',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'forbidden_topics',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_persona', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'zh'::character varying"))
    op.alter_column('ai_persona', 'tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'friendly'::character varying"))
    op.alter_column('ai_persona', 'system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ai_persona', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_kb_name'), 'ai_knowledge_base', ['name'], unique=False)
    op.create_index(op.f('idx_accountsendstats_stat_date'), 'accountsendstats', ['stat_date'], unique=False)
    op.create_index(op.f('idx_accountsendstats_account_id'), 'accountsendstats', ['account_id'], unique=False)
    op.drop_index(op.f('ix_account_status'), table_name='account')
    op.drop_index(op.f('ix_account_proxy_id'), table_name='account')
    op.drop_index(op.f('ix_account_last_active'), table_name='account')
    op.drop_index(op.f('ix_account_health_score'), table_name='account')
    op.drop_index(op.f('ix_account_created_at'), table_name='account')
    op.drop_index(op.f('ix_account_cooldown_until'), table_name='account')
    op.drop_index(op.f('ix_account_combat_role'), table_name='account')
    op.drop_index(op.f('ix_account_auto_reply'), table_name='account')
    op.create_index(op.f('idx_account_health_score'), 'account', ['health_score'], unique=False)
    op.create_index(op.f('idx_account_combat_role'), 'account', ['combat_role'], unique=False)
    op.alter_column('account', 'daily_action_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('account', 'health_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('account', 'combat_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'cannon'::character varying"))
    op.create_table('funnel_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'nurture'::character varying"), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('welcome_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_kick_ads', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('today_joined', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('today_left', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('funnel_group_campaign_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('funnel_group_pkey'))
    )
    op.create_index(op.f('idx_funnel_group_type'), 'funnel_group', ['type'], unique=False)
    op.create_index(op.f('idx_funnel_group_campaign'), 'funnel_group', ['campaign_id'], unique=False)
    op.create_table('source_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'traffic'::character varying"), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=10), server_default=sa.text("'low'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_scraped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('high_value_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ai_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source_group_pkey'))
    )
    op.create_index(op.f('idx_source_group_type'), 'source_group', ['type'], unique=False)
    op.create_index(op.f('idx_source_group_status'), 'source_group', ['status'], unique=False)
    # ### end Alembic commands ###
